
package org.filetransfer.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServiceInterface", targetNamespace = "http://services.filetransfer.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServiceInterface {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "uploadPDF", targetNamespace = "http://services.filetransfer.org/", className = "org.filetransfer.services.UploadPDF")
    @ResponseWrapper(localName = "uploadPDFResponse", targetNamespace = "http://services.filetransfer.org/", className = "org.filetransfer.services.UploadPDFResponse")
    public String uploadPDF(
        @WebParam(name = "arg0", targetNamespace = "")
        FileData arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns org.filetransfer.services.FileData
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "downloadPDF", targetNamespace = "http://services.filetransfer.org/", className = "org.filetransfer.services.DownloadPDF")
    @ResponseWrapper(localName = "downloadPDFResponse", targetNamespace = "http://services.filetransfer.org/", className = "org.filetransfer.services.DownloadPDFResponse")
    public FileData downloadPDF(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
